const fs = require('fs');
const path = require('path');

const ACTIVE_DIR = "F:\\WebApps\\1.ml_apps\\public\\data";
const STAGING_DIR = "F:\\WebApps\\1.ml_apps\\staging-data";

// 1. Load active data
const activeRankings = JSON.parse(fs.readFileSync(path.join(ACTIVE_DIR, 'rankings.json'), 'utf8'));
const activeMetrics = JSON.parse(fs.readFileSync(path.join(ACTIVE_DIR, 'model_metrics.json'), 'utf8'));
const activeCapture = JSON.parse(fs.readFileSync(path.join(ACTIVE_DIR, 'target_capture.json'), 'utf8'));
const activeScenarios = JSON.parse(fs.readFileSync(path.join(ACTIVE_DIR, 'scenarios.json'), 'utf8'));

// 2. Load staging data
const stagingRankings = JSON.parse(fs.readFileSync(path.join(STAGING_DIR, 'rankings.json'), 'utf8'));
const stagingMetrics = JSON.parse(fs.readFileSync(path.join(STAGING_DIR, 'model_metrics.json'), 'utf8'));
const stagingCapture = JSON.parse(fs.readFileSync(path.join(STAGING_DIR, 'target_capture.json'), 'utf8'));
const stagingScenarios = JSON.parse(fs.readFileSync(path.join(STAGING_DIR, 'scenarios.json'), 'utf8')); // this generated stagingScenarios by modifying the active one, but let's re-build it properly.

// 3. Merging logic
function isHistoris(scenario_id) {
    return scenario_id && scenario_id.startsWith('historis_');
}

const mergedRankings = [
    ...activeRankings.filter(r => !isHistoris(r.scenario_id)),
    ...stagingRankings
];

const mergedMetrics = [
    ...activeMetrics.filter(m => !isHistoris(m.scenario_id)),
    ...stagingMetrics
];

const mergedCapture = [
    ...activeCapture.filter(c => !isHistoris(c.scenario_id)),
    ...stagingCapture
];

// For scenarios, stagingScenarios was generated by modifying active, but just to be sure we do the same filter-append logic:
// Actually stagingScenarios was generated like this:
// const stagingScenarios = activeScenarios.map(...) from active. 
// Let's filter out historis from active, and we only have historis from staging scenarios? Wait, stagingScenarios had ALL of them previously but modified historis ones.
// Let's just use stagingScenarios as we built it correctly to have everything but with updated sources. Or explicitly merge:
const newHistorisScenarios = stagingScenarios.filter(s => isHistoris(s.scenario_id));
const mergedScenarios = [
    ...activeScenarios.filter(s => !isHistoris(s.scenario_id)),
    ...newHistorisScenarios
];

// 5. Write merged files to staging
fs.writeFileSync(path.join(STAGING_DIR, 'merged_rankings.json'), JSON.stringify(mergedRankings, null, 2));
fs.writeFileSync(path.join(STAGING_DIR, 'merged_model_metrics.json'), JSON.stringify(mergedMetrics, null, 2));
fs.writeFileSync(path.join(STAGING_DIR, 'merged_target_capture.json'), JSON.stringify(mergedCapture, null, 2));
fs.writeFileSync(path.join(STAGING_DIR, 'merged_scenarios.json'), JSON.stringify(mergedScenarios, null, 2));

console.log("=== MERGE SUCCESSFUL ===");

// 6. Validation
console.log("\n=== VALIDATION REPORT (MERGED) ===");

const totalRows = mergedRankings.length;
const historisRows = mergedRankings.filter(r => isHistoris(r.scenario_id)).length;
const normatifRows = mergedRankings.filter(r => !isHistoris(r.scenario_id)).length;

console.log(`\nRow Counts:`);
console.log(`- Total rows: ${totalRows}`);
console.log(`- Historis row count: ${historisRows}`);
console.log(`- Normatif row count (preserved): ${normatifRows}`);

const uniqueScenarios = [...new Set(mergedRankings.map(r => r.scenario_id))];
console.log(`\n- Scenario_id list: ${uniqueScenarios.join(', ')}`);

const uniqueModels = [...new Set(mergedRankings.map(r => r.model))];
console.log(`- Model list: ${uniqueModels.join(', ')}`);

const uniqueScoreTypes = [...new Set(mergedRankings.map(r => r.score_type))];
console.log(`- Score_type list: ${uniqueScoreTypes.filter(Boolean).join(', ')}`);

// duplicate key check: scenario_id + model + score_type + road_name
let duplicates = 0;
const keySet = new Set();
let missingRoadNames = 0;

for (const r of mergedRankings) {
    if (!r.road_name) missingRoadNames++;
    const st = r.score_type || 'pred_prob';
    const key = `${r.scenario_id}|${r.model}|${st}|${r.road_name}`;
    if (keySet.has(key)) duplicates++;
    else keySet.add(key);
}

console.log(`- Duplicate key check (scenario+model+score_type+road_name): ${duplicates}`);
console.log(`- Missing road_name count: ${missingRoadNames}`);


// target truth counts
const targetRows = JSON.parse(fs.readFileSync(path.join(ACTIVE_DIR, 'target_rows.json'), 'utf8'));
const truthCounts = {
    planned_any_2026: 0,
    planned_tender_2026: 0,
    planned_pl_2026: 0,
    planned_teknokratis_2026: 0,
    planned_teknokratis_2027: 0
};
const roadTruth = new Map();
for (const r of targetRows) {
    const nm = r.road_name.trim().toLowerCase();
    if (!roadTruth.has(nm)) {
        roadTruth.set(nm, true);
        truthCounts.planned_any_2026 += r.planned_any_2026 ? 1 : 0;
        truthCounts.planned_tender_2026 += r.planned_tender_2026 ? 1 : 0;
        truthCounts.planned_pl_2026 += r.planned_pl_2026 ? 1 : 0;
        truthCounts.planned_teknokratis_2026 += r.planned_teknokratis_2026 ? 1 : 0;
        truthCounts.planned_teknokratis_2027 += r.planned_teknokratis_2027 ? 1 : 0;
    }
}

console.log(`\n- Target truth counts (from untouched target_rows.json):`);
console.log(`  planned_any_2026: ${truthCounts.planned_any_2026}`);
console.log(`  planned_tender_2026: ${truthCounts.planned_tender_2026}`);
console.log(`  planned_pl_2026: ${truthCounts.planned_pl_2026}`);
console.log(`  planned_teknokratis_2026: ${truthCounts.planned_teknokratis_2026}`);
console.log(`  planned_teknokratis_2027: ${truthCounts.planned_teknokratis_2027}`);
